import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { Header } from "@/components/Header";
import Providers from "@/providers";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersData = await headers();
  const cookies = headersData.get("cookie");

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Providers cookies={cookies}>
          <div className="flex min-h-[100dvh] w-full flex-col items-center">
            <Header />
            <main className="flex w-full max-w-screen-xl flex-grow flex-col p-4">{children}</main>
            <div>FOOTER</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
