import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import Providers from "@/providers";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        <Providers>
          <div className="mx-auto flex min-h-[100dvh] w-full max-w-[1182px] flex-col items-center px-4">
            <Header />
            <main className="flex w-full flex-grow pt-8">{children}</main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}

export const dynamic = "force-static";
export const revalidate = 300; // 5min
